### PR TITLE
Add 1.8 support

### LINKED ISSUE #9: 1.8 protocol support
Velocity doesn't currently support Minecraft 1.8. This can be a good issue to tackle if you have some familiarity with the Minecraft protocol on a low level.

Links that may help you:

* [wiki.vg](http://wiki.vg/index.php?title=Protocol&oldid=7368)

### PR DESCRIPTION
**Pull request by Desetude**
Implemented the 1.8 protocol by reversing the 1.8 to 1.9 changelog on https://wiki.vg/Protocol_History. I have tested this with a variety of different actions/packets and it seems to function correctly. 
Closes #9.

### CODE REVIEW

**Comment by astei** [comment]
Thanks, will take a look at this later today.

**Comment by astei** [comment]
Did you make sure to try out server connecting? I heard that 1.8 may have issues with that (see #7 for a related conversation).

I don't have a "proper" connection command yet, but `/connect` will try to connect you to the server on localhost port 25566.

**Comment by Desetude** [comment]
Just checked, server connecting does work.

**Comment by MatrixTunnel** [comment]
Have you tried connecting with multiple clients? (on different and same versions)

**Comment by Desetude** [comment]
Yes, multiple clients on the same and on different versions works.

**Comment by astei** [comment]
LGTM

**Pull request merged**
