### PR TITLE
Add .idea to .gitignore file

### PR DESCRIPTION
**Pull request by MatrixTunnel**

### CODE REVIEW

**Comment by astei** [comment]
`.idea` should already be excluded considering the rest of the `.gitignore` names specific files to exclude.

**Comment by MatrixTunnel** [comment]
It technically is but some files I have locally aren't being excluded as you can see here https://i.imgur.com/vPdupHC.png

Might just be something on my end ¯\\\_(ツ)\_/¯

**Comment by electronicboy** [comment]
the .idea folder has stuff which is actually useful for sharing, it's more the concept of user-specific/"high churn" files which you don't want in the repo, configs for stuff like code styling are useful to others and are fin to be in the repo

**Comment by MatrixTunnel** [comment]
Ah, I forgot about that. Thanks :)

**Pull request closed without merging**
